apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        serviceAnnotations:
          kubernetes.civo.com/ipv4-address: $IP2
    - name: istio-ewgw
      enabled: true
  values:
    global:
      meshID: rejekts
      multiCluster:
        enabled: true
        clusterName: rejekts2
      network: rejekts2
  meshConfig:
    accessLogFile: "/dev/stdout"
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
