apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argo-rollouts
  namespace: argo-rollouts
spec:
  parentRefs:
  - name: http
    namespace: istio-system
  hostnames: ["rollouts.rejekts.kubespaces.io"]
  rules:
  - backendRefs:
    - name: argo-rollouts-dashboard
      port: 3100
