apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: prometheus
spec:
  parentRefs:
  - name: http
    namespace: istio-system
  hostnames: ["grafana.rejekts.kubespaces.io"]
  rules:
  - backendRefs:
    - name: prom-grafana
      port: 80
