apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: hubble-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  addresses:
  - value: istio-ingressgateway.istio-system.svc.cluster.local
    type: Hostname
  listeners:
  - name: default
    hostname: "hubble.rejekts.kubespaces.io"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hubble
  namespace: kube-system
spec:
  parentRefs:
  - name: hubble-gateway
    namespace: istio-system
  hostnames: ["hubble.rejekts.kubespaces.io"]
  rules:
  - backendRefs:
    - name: hubble-ui
      port: 80
